# theme: jekyll-theme-Business
# title: Tuấn Anh's pages
# description: Bookmark this to keep an eye on my project updates!

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-Odyssey
title: Tuấn Anh's Page
email: nt.anh.fai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Các dự án tôi đã hoàn thành và muốn share cho mọi người.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ntanhfai.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Foxconn
address_line: Bắc Giang, Việt Nam
telephone_number: 0988086099
fax_number: 
company_email: 
google_map: 

# Social Link
facebook_link: https://web.facebook.com/anh211
twitter_link:  
linkedin_link: https://www.linkedin.com/in/tu%E1%BA%A5n-anh-nguy%E1%BB%85n-008771294/
 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/